server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Practice/financecore/financecore-config
#          uri: "https://github.com/Roshan1206/financecore-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

